title: "Oh My OpenWrt"
description: Oh My OpenWrt
# theme: just-the-docs
remote_theme: stuarthua/just-the-docs
color_scheme: "nil"
search_enabled: false
heading_anchors: true
lang: zh_cn
aux_links:
  "Oh My OpenWrt on GitHub":
    - "//github.com/stuarthua/oh-my-openwrt"